before:
  hooks:
    - make compile_frontend static_assets
builds:
  - main: ./cmd/gaia/main.go
    binary: gaia-{{ .Os }}-{{ .Arch }}
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
    - "gaiapipeline/gaia:latest"
    - "gaiapipeline/gaia:{{ .Tag }}"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile
    extra_files:
    - docker/docker-entrypoint.sh
    - docker/settings-docker.xml
  - image_templates:
    - "gaiapipeline/gaia:latest-go"
    - "gaiapipeline/gaia:{{ .Tag }}-go"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile.golang
    extra_files:
    - docker/docker-entrypoint.sh
  - image_templates:
    - "gaiapipeline/gaia:latest-java"
    - "gaiapipeline/gaia:{{ .Tag }}-java"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile.java
    extra_files:
    - docker/docker-entrypoint.sh
    - docker/settings-docker.xml
  - image_templates:
    - "gaiapipeline/gaia:latest-python"
    - "gaiapipeline/gaia:{{ .Tag }}-python"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile.python
    extra_files:
    - docker/docker-entrypoint.sh
  - image_templates:
    - "gaiapipeline/gaia:latest-cpp"
    - "gaiapipeline/gaia:{{ .Tag }}-cpp"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile.cpp
    extra_files:
    - docker/docker-entrypoint.sh
  - image_templates:
    - "gaiapipeline/gaia:latest-ruby"
    - "gaiapipeline/gaia:{{ .Tag }}-ruby"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile.ruby
    extra_files:
    - docker/docker-entrypoint.sh
  - image_templates:
    - "gaiapipeline/gaia:latest-nodejs"
    - "gaiapipeline/gaia:{{ .Tag }}-nodejs"
    binaries:
    - gaia-linux-amd64
    dockerfile: docker/Dockerfile.nodejs
    extra_files:
    - docker/docker-entrypoint.sh
