before:
  hooks:
    - make compile_frontend static_assets
builds:
  - main: ./cmd/gaia/main.go
    binary: gaia-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: true
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile
    extra_files:
      - docker/docker-entrypoint.sh
      - docker/settings-docker.xml
    tag_templates:
    - latest
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.golang
    extra_files:
      - docker/docker-entrypoint.sh
    tag_templates:
    - "{{ .Tag }}-go"
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.java
    extra_files:
      - docker/docker-entrypoint.sh
      - docker/settings-docker.xml
    tag_templates:
    - "{{ .Tag }}-java"
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.python
    extra_files:
      - docker/docker-entrypoint.sh
    tag_templates:
    - "{{ .Tag }}-python"
  - image: gaiapipeline/gaia
    skip_push: false
    binary: gaia-linux-amd64
    dockerfile: docker/Dockerfile.cpp
    extra_files:
      - docker/docker-entrypoint.sh
    tag_templates:
    - "{{ .Tag  }}-cpp"
