// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	plugin.proto

It has these top-level messages:
	Job
	Question
	JobResult
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Job represents a single job
type Job struct {
	UniqueId    string    `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	Title       string    `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string    `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Priority    int32     `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	Question    *Question `protobuf:"bytes,5,opt,name=question" json:"question,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto1.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Job) GetQuestion() *Question {
	if m != nil {
		return m.Question
	}
	return nil
}

// Question represents a manual question
type Question struct {
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Answer      string `protobuf:"bytes,3,opt,name=answer" json:"answer,omitempty"`
}

func (m *Question) Reset()                    { *m = Question{} }
func (m *Question) String() string            { return proto1.CompactTextString(m) }
func (*Question) ProtoMessage()               {}
func (*Question) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Question) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Question) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Question) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

// JobResult represents the result of an executed job
type JobResult struct {
	UniqueId     string `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId" json:"unique_id,omitempty"`
	Failed       bool   `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	ExitPipeline bool   `protobuf:"varint,3,opt,name=exit_pipeline,json=exitPipeline" json:"exit_pipeline,omitempty"`
	Message      string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *JobResult) Reset()                    { *m = JobResult{} }
func (m *JobResult) String() string            { return proto1.CompactTextString(m) }
func (*JobResult) ProtoMessage()               {}
func (*JobResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JobResult) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *JobResult) GetFailed() bool {
	if m != nil {
		return m.Failed
	}
	return false
}

func (m *JobResult) GetExitPipeline() bool {
	if m != nil {
		return m.ExitPipeline
	}
	return false
}

func (m *JobResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Empty message
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*Job)(nil), "proto.Job")
	proto1.RegisterType((*Question)(nil), "proto.Question")
	proto1.RegisterType((*JobResult)(nil), "proto.JobResult")
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Plugin service

type PluginClient interface {
	// GetJobs returns a stream of Job objects.
	// Used to expose jobs to gaia.
	GetJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Plugin_GetJobsClient, error)
	// ExecuteJob signals the plugin to execute the given job.
	// Used to execute one job from a pipeline.
	ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobResult, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) GetJobs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Plugin_GetJobsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Plugin_serviceDesc.Streams[0], c.cc, "/proto.Plugin/GetJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginGetJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Plugin_GetJobsClient interface {
	Recv() (*Job, error)
	grpc.ClientStream
}

type pluginGetJobsClient struct {
	grpc.ClientStream
}

func (x *pluginGetJobsClient) Recv() (*Job, error) {
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pluginClient) ExecuteJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*JobResult, error) {
	out := new(JobResult)
	err := grpc.Invoke(ctx, "/proto.Plugin/ExecuteJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Plugin service

type PluginServer interface {
	// GetJobs returns a stream of Job objects.
	// Used to expose jobs to gaia.
	GetJobs(*Empty, Plugin_GetJobsServer) error
	// ExecuteJob signals the plugin to execute the given job.
	// Used to execute one job from a pipeline.
	ExecuteJob(context.Context, *Job) (*JobResult, error)
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_GetJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).GetJobs(m, &pluginGetJobsServer{stream})
}

type Plugin_GetJobsServer interface {
	Send(*Job) error
	grpc.ServerStream
}

type pluginGetJobsServer struct {
	grpc.ServerStream
}

func (x *pluginGetJobsServer) Send(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func _Plugin_ExecuteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).ExecuteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/ExecuteJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).ExecuteJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteJob",
			Handler:    _Plugin_ExecuteJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetJobs",
			Handler:       _Plugin_GetJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

func init() { proto1.RegisterFile("plugin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x89, 0x5b, 0xbb, 0xf6, 0x36, 0x51, 0x0e, 0x19, 0x65, 0xbe, 0x94, 0x8a, 0x30, 0x14,
	0x86, 0xcc, 0xcf, 0x30, 0xc4, 0x3e, 0xcd, 0x3c, 0x09, 0x3e, 0x8c, 0x75, 0x3d, 0x47, 0xa0, 0x6b,
	0xb2, 0x26, 0xc5, 0xed, 0xc9, 0x0f, 0xe3, 0x17, 0x95, 0xa5, 0xe9, 0x1c, 0x0a, 0x3e, 0xe5, 0xfe,
	0xbf, 0xbb, 0xe4, 0x2e, 0xff, 0x83, 0x81, 0x2a, 0xea, 0xb5, 0x28, 0x27, 0xaa, 0x92, 0x46, 0xa2,
	0x67, 0x8f, 0xe4, 0x8b, 0x41, 0x27, 0x95, 0x19, 0x5e, 0x43, 0x58, 0x97, 0x62, 0x5b, 0xd3, 0x42,
	0xe4, 0x11, 0x8b, 0xd9, 0x38, 0xe4, 0x41, 0x03, 0x9e, 0x73, 0xbc, 0x02, 0xcf, 0x08, 0x53, 0x50,
	0x74, 0x66, 0x13, 0x8d, 0xc0, 0x18, 0xfa, 0x39, 0xe9, 0x55, 0x25, 0x94, 0x11, 0xb2, 0x8c, 0x3a,
	0x36, 0x77, 0x8a, 0x70, 0x04, 0x81, 0xaa, 0x84, 0xac, 0x84, 0xd9, 0x47, 0xdd, 0x98, 0x8d, 0x3d,
	0x7e, 0xd4, 0x78, 0x0f, 0xc1, 0xb6, 0x26, 0x6d, 0xaf, 0x7a, 0x31, 0x1b, 0xf7, 0xa7, 0x17, 0xcd,
	0x64, 0x93, 0x17, 0x87, 0xf9, 0xb1, 0x20, 0x79, 0x85, 0xa0, 0xa5, 0xbf, 0xdb, 0xb2, 0xbf, 0x6d,
	0x11, 0xba, 0x66, 0xaf, 0xda, 0x69, 0x6d, 0x8c, 0x43, 0xf0, 0x97, 0xa5, 0xfe, 0xa0, 0xca, 0xcd,
	0xe9, 0x54, 0xf2, 0x09, 0x61, 0x2a, 0x33, 0x4e, 0xba, 0x2e, 0xcc, 0xff, 0x26, 0x0c, 0xc1, 0x7f,
	0x5f, 0x8a, 0x82, 0x72, 0xfb, 0x6e, 0xc0, 0x9d, 0xc2, 0x1b, 0x38, 0xa7, 0x9d, 0x30, 0x0b, 0x25,
	0x14, 0x15, 0xa2, 0x24, 0xdb, 0x20, 0xe0, 0x83, 0x03, 0x9c, 0x3b, 0x86, 0x11, 0xf4, 0x36, 0xa4,
	0xf5, 0x72, 0x4d, 0xd6, 0x88, 0x90, 0xb7, 0x32, 0xe9, 0x81, 0x37, 0xdb, 0x28, 0xb3, 0x9f, 0xbe,
	0x81, 0x3f, 0xb7, 0x0b, 0xc2, 0x5b, 0xe8, 0x3d, 0x91, 0x49, 0x65, 0xa6, 0x71, 0xe0, 0x3c, 0xb1,
	0x25, 0x23, 0x70, 0x2a, 0x95, 0xd9, 0x03, 0xc3, 0x3b, 0x80, 0xd9, 0x8e, 0x56, 0xb5, 0xa1, 0xc3,
	0x02, 0x4f, 0x72, 0xa3, 0xcb, 0x9f, 0xb8, 0xf9, 0x59, 0xe6, 0x5b, 0xf0, 0xf8, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x88, 0xf1, 0x76, 0xd4, 0x04, 0x02, 0x00, 0x00,
}
