// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker.proto

package worker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// WorkerInstance represents the identity of
// a worker instance.
type WorkerInstance struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	WorkerSlots          int32    `protobuf:"varint,2,opt,name=worker_slots,json=workerSlots,proto3" json:"worker_slots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerInstance) Reset()         { *m = WorkerInstance{} }
func (m *WorkerInstance) String() string { return proto.CompactTextString(m) }
func (*WorkerInstance) ProtoMessage()    {}
func (*WorkerInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{0}
}

func (m *WorkerInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerInstance.Unmarshal(m, b)
}
func (m *WorkerInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerInstance.Marshal(b, m, deterministic)
}
func (m *WorkerInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerInstance.Merge(m, src)
}
func (m *WorkerInstance) XXX_Size() int {
	return xxx_messageInfo_WorkerInstance.Size(m)
}
func (m *WorkerInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerInstance.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerInstance proto.InternalMessageInfo

func (m *WorkerInstance) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *WorkerInstance) GetWorkerSlots() int32 {
	if m != nil {
		return m.WorkerSlots
	}
	return 0
}

// PipelineRun represents one pipeline run.
type PipelineRun struct {
	UniqueId             string   `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StartDate            int64    `protobuf:"varint,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	FinishDate           int64    `protobuf:"varint,5,opt,name=finish_date,json=finishDate,proto3" json:"finish_date,omitempty"`
	ScheduleDate         int64    `protobuf:"varint,6,opt,name=schedule_date,json=scheduleDate,proto3" json:"schedule_date,omitempty"`
	PipelineId           int64    `protobuf:"varint,7,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	PipelineName         string   `protobuf:"bytes,8,opt,name=pipeline_name,json=pipelineName,proto3" json:"pipeline_name,omitempty"`
	PipelineType         string   `protobuf:"bytes,9,opt,name=pipeline_type,json=pipelineType,proto3" json:"pipeline_type,omitempty"`
	ShaSum               []byte   `protobuf:"bytes,10,opt,name=sha_sum,json=shaSum,proto3" json:"sha_sum,omitempty"`
	Jobs                 []*Job   `protobuf:"bytes,11,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PipelineRun) Reset()         { *m = PipelineRun{} }
func (m *PipelineRun) String() string { return proto.CompactTextString(m) }
func (*PipelineRun) ProtoMessage()    {}
func (*PipelineRun) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{1}
}

func (m *PipelineRun) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineRun.Unmarshal(m, b)
}
func (m *PipelineRun) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineRun.Marshal(b, m, deterministic)
}
func (m *PipelineRun) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineRun.Merge(m, src)
}
func (m *PipelineRun) XXX_Size() int {
	return xxx_messageInfo_PipelineRun.Size(m)
}
func (m *PipelineRun) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineRun.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineRun proto.InternalMessageInfo

func (m *PipelineRun) GetUniqueId() string {
	if m != nil {
		return m.UniqueId
	}
	return ""
}

func (m *PipelineRun) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PipelineRun) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PipelineRun) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *PipelineRun) GetFinishDate() int64 {
	if m != nil {
		return m.FinishDate
	}
	return 0
}

func (m *PipelineRun) GetScheduleDate() int64 {
	if m != nil {
		return m.ScheduleDate
	}
	return 0
}

func (m *PipelineRun) GetPipelineId() int64 {
	if m != nil {
		return m.PipelineId
	}
	return 0
}

func (m *PipelineRun) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

func (m *PipelineRun) GetPipelineType() string {
	if m != nil {
		return m.PipelineType
	}
	return ""
}

func (m *PipelineRun) GetShaSum() []byte {
	if m != nil {
		return m.ShaSum
	}
	return nil
}

func (m *PipelineRun) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// Job represents one job from a pipeline run.
type Job struct {
	UniqueId             uint32      `protobuf:"varint,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Title                string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DependsOn            []*Job      `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Status               string      `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Args                 []*Argument `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetUniqueId() uint32 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func (m *Job) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetDependsOn() []*Job {
	if m != nil {
		return m.DependsOn
	}
	return nil
}

func (m *Job) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Job) GetArgs() []*Argument {
	if m != nil {
		return m.Args
	}
	return nil
}

// Argument represents one argument from a job.
type Argument struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Argument) Reset()         { *m = Argument{} }
func (m *Argument) String() string { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()    {}
func (*Argument) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{3}
}

func (m *Argument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Argument.Unmarshal(m, b)
}
func (m *Argument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Argument.Marshal(b, m, deterministic)
}
func (m *Argument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Argument.Merge(m, src)
}
func (m *Argument) XXX_Size() int {
	return xxx_messageInfo_Argument.Size(m)
}
func (m *Argument) XXX_DiscardUnknown() {
	xxx_messageInfo_Argument.DiscardUnknown(m)
}

var xxx_messageInfo_Argument proto.InternalMessageInfo

func (m *Argument) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Argument) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Argument) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Argument) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// BinaryChunk represents one chunk of a binary.
type BinaryChunk struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryChunk) Reset()         { *m = BinaryChunk{} }
func (m *BinaryChunk) String() string { return proto.CompactTextString(m) }
func (*BinaryChunk) ProtoMessage()    {}
func (*BinaryChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ff6184b07e587a, []int{4}
}

func (m *BinaryChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryChunk.Unmarshal(m, b)
}
func (m *BinaryChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryChunk.Marshal(b, m, deterministic)
}
func (m *BinaryChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryChunk.Merge(m, src)
}
func (m *BinaryChunk) XXX_Size() int {
	return xxx_messageInfo_BinaryChunk.Size(m)
}
func (m *BinaryChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryChunk.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryChunk proto.InternalMessageInfo

func (m *BinaryChunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func init() {
	proto.RegisterType((*WorkerInstance)(nil), "worker.WorkerInstance")
	proto.RegisterType((*PipelineRun)(nil), "worker.PipelineRun")
	proto.RegisterType((*Job)(nil), "worker.Job")
	proto.RegisterType((*Argument)(nil), "worker.Argument")
	proto.RegisterType((*BinaryChunk)(nil), "worker.BinaryChunk")
}

func init() { proto.RegisterFile("worker.proto", fileDescriptor_e4ff6184b07e587a) }

var fileDescriptor_e4ff6184b07e587a = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0xc4, 0x71, 0xeb, 0xb1, 0x5b, 0x55, 0x0b, 0x2a, 0x56, 0x2b, 0xd4, 0x90, 0x72,
	0x88, 0x38, 0xa4, 0x55, 0x91, 0x10, 0x20, 0x2e, 0x40, 0x11, 0x4a, 0x0f, 0x10, 0x39, 0x20, 0x8e,
	0xd1, 0x26, 0x9e, 0xda, 0x4b, 0xec, 0xb5, 0xd9, 0x0f, 0x50, 0x9e, 0x8a, 0x97, 0xe0, 0x31, 0x78,
	0x18, 0xe4, 0x5d, 0xbb, 0x4a, 0x48, 0x8b, 0xc4, 0x6d, 0xe7, 0x3f, 0xbf, 0x99, 0x9d, 0x99, 0xdd,
	0x81, 0xf0, 0x47, 0x29, 0x96, 0x28, 0x46, 0x95, 0x28, 0x55, 0x49, 0x3c, 0x6b, 0x1d, 0x1d, 0xa7,
	0x65, 0x99, 0xe6, 0x78, 0x66, 0xd4, 0xb9, 0xbe, 0x3e, 0xc3, 0xa2, 0x52, 0x2b, 0x0b, 0x0d, 0x26,
	0xb0, 0xff, 0xc5, 0x60, 0x63, 0x2e, 0x15, 0xe5, 0x0b, 0x24, 0xc7, 0xe0, 0x6b, 0xce, 0xbe, 0x69,
	0x9c, 0xb1, 0x24, 0x72, 0xfa, 0xce, 0xd0, 0x8f, 0x77, 0xad, 0x30, 0x4e, 0xc8, 0xa3, 0xf6, 0x8e,
	0x99, 0xcc, 0x4b, 0x25, 0xa3, 0x4e, 0xdf, 0x19, 0xf6, 0xe2, 0xc0, 0x6a, 0xd3, 0x5a, 0x1a, 0xfc,
	0xee, 0x40, 0x30, 0x61, 0x15, 0xe6, 0x8c, 0x63, 0xac, 0xf9, 0xbf, 0xf3, 0xed, 0x43, 0x87, 0x25,
	0x26, 0x4b, 0x37, 0xee, 0xb0, 0x84, 0x1c, 0x82, 0x27, 0x15, 0x55, 0x5a, 0x46, 0x5d, 0x43, 0x36,
	0x16, 0x79, 0x08, 0x20, 0x15, 0x15, 0x6a, 0x96, 0x50, 0x85, 0x91, 0x6b, 0x78, 0xdf, 0x28, 0x97,
	0x54, 0x21, 0x39, 0x81, 0xe0, 0x9a, 0x71, 0x26, 0x33, 0xeb, 0xef, 0x19, 0x3f, 0x58, 0xc9, 0x00,
	0xa7, 0xb0, 0x27, 0x17, 0x19, 0x26, 0x3a, 0x47, 0x8b, 0x78, 0x06, 0x09, 0x5b, 0xb1, 0xcd, 0x52,
	0x35, 0x85, 0xd7, 0xb5, 0xee, 0xd8, 0x2c, 0xad, 0x34, 0x4e, 0xea, 0x2c, 0x37, 0x00, 0xa7, 0x05,
	0x46, 0xbb, 0xa6, 0xc8, 0xb0, 0x15, 0x3f, 0xd0, 0x02, 0x37, 0x20, 0xb5, 0xaa, 0x30, 0xf2, 0x37,
	0xa1, 0x4f, 0xab, 0x0a, 0xc9, 0x03, 0xd8, 0x91, 0x19, 0x9d, 0x49, 0x5d, 0x44, 0xd0, 0x77, 0x86,
	0x61, 0xec, 0xc9, 0x8c, 0x4e, 0x75, 0x41, 0x4e, 0xc0, 0xfd, 0x5a, 0xce, 0x65, 0x14, 0xf4, 0xbb,
	0xc3, 0xe0, 0x22, 0x18, 0x35, 0x2f, 0x7a, 0x55, 0xce, 0x63, 0xe3, 0x18, 0xfc, 0x72, 0xa0, 0x7b,
	0x55, 0xce, 0xb7, 0xc7, 0xba, 0xb7, 0x36, 0xd6, 0xfb, 0xd0, 0x53, 0x4c, 0xe5, 0x68, 0x26, 0xeb,
	0xc7, 0xd6, 0x20, 0x7d, 0x08, 0x12, 0x94, 0x0b, 0xc1, 0x2a, 0xc5, 0x4a, 0xde, 0x4c, 0x78, 0x5d,
	0x22, 0x4f, 0x00, 0x12, 0xac, 0x90, 0x27, 0x72, 0x56, 0xf2, 0xc8, 0xdd, 0xae, 0xc1, 0x6f, 0xdc,
	0x1f, 0xf9, 0xda, 0x53, 0xf5, 0x36, 0x9e, 0xea, 0x31, 0xb8, 0x54, 0xa4, 0x32, 0xf2, 0x4c, 0xf4,
	0x41, 0x1b, 0xfd, 0x5a, 0xa4, 0xba, 0x40, 0xae, 0x62, 0xe3, 0x1d, 0x64, 0xb0, 0xdb, 0x2a, 0x7f,
	0xd7, 0xe5, 0x6c, 0xd7, 0x45, 0xc0, 0x35, 0xa3, 0xb4, 0xed, 0x98, 0x33, 0x39, 0x80, 0xee, 0x12,
	0x57, 0x4d, 0x17, 0xf5, 0xb1, 0xee, 0xfa, 0x3b, 0xcd, 0xb5, 0xfd, 0x1f, 0x7e, 0x6c, 0x8d, 0xc1,
	0x29, 0x04, 0x6f, 0x18, 0xa7, 0x62, 0xf5, 0x36, 0xd3, 0x7c, 0x59, 0x43, 0x8b, 0xfa, 0x60, 0xae,
	0x09, 0x63, 0x6b, 0x5c, 0xfc, 0xec, 0x80, 0x67, 0xf7, 0x80, 0x3c, 0x03, 0x77, 0xc2, 0x78, 0x4a,
	0x0e, 0xdb, 0xca, 0x37, 0xf7, 0xe3, 0xe8, 0x70, 0x64, 0xf7, 0x69, 0xd4, 0xee, 0xd3, 0xe8, 0x5d,
	0xbd, 0x4f, 0xe4, 0x39, 0xec, 0xbc, 0x47, 0x55, 0xc3, 0x77, 0x86, 0xde, 0x6b, 0xf5, 0xb5, 0xfd,
	0x38, 0x77, 0xc8, 0x0b, 0x80, 0xcf, 0x55, 0xfd, 0x2b, 0x4d, 0xf0, 0x6d, 0xd0, 0x9d, 0x97, 0xbe,
	0x84, 0x70, 0xaa, 0x04, 0xd2, 0xc2, 0xb6, 0x78, 0x7b, 0xf0, 0x8d, 0xb8, 0x36, 0x87, 0x73, 0x87,
	0xbc, 0x02, 0xb8, 0x44, 0x81, 0x29, 0x93, 0x0a, 0xc5, 0xff, 0xb6, 0x3b, 0xf7, 0x8c, 0xfd, 0xf4,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x1b, 0x22, 0x00, 0x74, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerClient interface {
	// Ping is used to send a ping response.
	Ping(ctx context.Context, in *WorkerInstance, opts ...grpc.CallOption) (*empty.Empty, error)
	// GetWork pulls work from the primary instance.
	GetWork(ctx context.Context, in *WorkerInstance, opts ...grpc.CallOption) (Worker_GetWorkClient, error)
	// UpdateWork updates work information at the primary instance.
	UpdateWork(ctx context.Context, in *PipelineRun, opts ...grpc.CallOption) (*empty.Empty, error)
	// StreamBinary streams a pipeline binary back to a worker instance.
	StreamBinary(ctx context.Context, in *PipelineRun, opts ...grpc.CallOption) (Worker_StreamBinaryClient, error)
	// Deregister deregister a registered worker from the primary instance.
	Deregister(ctx context.Context, in *WorkerInstance, opts ...grpc.CallOption) (*empty.Empty, error)
}

type workerClient struct {
	cc *grpc.ClientConn
}

func NewWorkerClient(cc *grpc.ClientConn) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) Ping(ctx context.Context, in *WorkerInstance, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/worker.Worker/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetWork(ctx context.Context, in *WorkerInstance, opts ...grpc.CallOption) (Worker_GetWorkClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Worker_serviceDesc.Streams[0], "/worker.Worker/GetWork", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerGetWorkClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_GetWorkClient interface {
	Recv() (*PipelineRun, error)
	grpc.ClientStream
}

type workerGetWorkClient struct {
	grpc.ClientStream
}

func (x *workerGetWorkClient) Recv() (*PipelineRun, error) {
	m := new(PipelineRun)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) UpdateWork(ctx context.Context, in *PipelineRun, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/worker.Worker/UpdateWork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) StreamBinary(ctx context.Context, in *PipelineRun, opts ...grpc.CallOption) (Worker_StreamBinaryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Worker_serviceDesc.Streams[1], "/worker.Worker/StreamBinary", opts...)
	if err != nil {
		return nil, err
	}
	x := &workerStreamBinaryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_StreamBinaryClient interface {
	Recv() (*BinaryChunk, error)
	grpc.ClientStream
}

type workerStreamBinaryClient struct {
	grpc.ClientStream
}

func (x *workerStreamBinaryClient) Recv() (*BinaryChunk, error) {
	m := new(BinaryChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) Deregister(ctx context.Context, in *WorkerInstance, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/worker.Worker/Deregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
type WorkerServer interface {
	// Ping is used to send a ping response.
	Ping(context.Context, *WorkerInstance) (*empty.Empty, error)
	// GetWork pulls work from the primary instance.
	GetWork(*WorkerInstance, Worker_GetWorkServer) error
	// UpdateWork updates work information at the primary instance.
	UpdateWork(context.Context, *PipelineRun) (*empty.Empty, error)
	// StreamBinary streams a pipeline binary back to a worker instance.
	StreamBinary(*PipelineRun, Worker_StreamBinaryServer) error
	// Deregister deregister a registered worker from the primary instance.
	Deregister(context.Context, *WorkerInstance) (*empty.Empty, error)
}

func RegisterWorkerServer(s *grpc.Server, srv WorkerServer) {
	s.RegisterService(&_Worker_serviceDesc, srv)
}

func _Worker_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.Worker/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Ping(ctx, req.(*WorkerInstance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetWork_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkerInstance)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).GetWork(m, &workerGetWorkServer{stream})
}

type Worker_GetWorkServer interface {
	Send(*PipelineRun) error
	grpc.ServerStream
}

type workerGetWorkServer struct {
	grpc.ServerStream
}

func (x *workerGetWorkServer) Send(m *PipelineRun) error {
	return x.ServerStream.SendMsg(m)
}

func _Worker_UpdateWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineRun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).UpdateWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.Worker/UpdateWork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).UpdateWork(ctx, req.(*PipelineRun))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_StreamBinary_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineRun)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).StreamBinary(m, &workerStreamBinaryServer{stream})
}

type Worker_StreamBinaryServer interface {
	Send(*BinaryChunk) error
	grpc.ServerStream
}

type workerStreamBinaryServer struct {
	grpc.ServerStream
}

func (x *workerStreamBinaryServer) Send(m *BinaryChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _Worker_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerInstance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/worker.Worker/Deregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).Deregister(ctx, req.(*WorkerInstance))
	}
	return interceptor(ctx, in, info, handler)
}

var _Worker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "worker.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Worker_Ping_Handler,
		},
		{
			MethodName: "UpdateWork",
			Handler:    _Worker_UpdateWork_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _Worker_Deregister_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWork",
			Handler:       _Worker_GetWork_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBinary",
			Handler:       _Worker_StreamBinary_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}
